# Generated by Django 4.2.5 on 2023-09-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='lng',
            field=models.FloatField(),
        ),
    ]
